# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicearea',
            old_name='geojson_data',
            new_name='polygon',
        ),
    ]
